//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webServer.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public int productCategory { get; set; }
        public string productName { get; set; }
        public string productDescription { get; set; }
        public int productRegularPrice { get; set; }
        public int productSalePrice { get; set; }
        public int productQuantity { get; set; }
        public int productStatus { get; set; }
        public string productImage { get; set; }
        public string productImageAltText { get; set; }
    }
}
